# Project identification
sonar.projectKey=DwiAlwinto_Inlislite-v3.3
sonar.organization=dwialwinto

# Scan folder app saja (kode Anda sendiri)
sonar.sources=app,public

# Bahasa
sonar.language=php

# Exclusions - semua library dan generated files
sonar.exclusions=\
  **/vendor/**,\
  **/vendors/**,\
  **/node_modules/**,\
  **/bower_components/**,\
  **/.github/**,\
  **/tests/**,\
  **/dist/**,\
  **/build/**,\
  **/*.min.js,\
  **/*.min.css,\
  public/assets/vendors/**,\
  public/assets/plugins/**,\
  public/assets/js/vendor/**,\
  writable/**,\
  user_guide_src/**